packages:
  - "packages/*"
  - "packages/thingd-cli/src/dashboard/frontend"

allowBuilds:
  '@nestjs/core': set this to true or false
  'esbuild': true
  lefthook: true

minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
