packages:
  - packages/*
  - packages/thingd-cli/src/dashboard/frontend
  - examples/*

allowBuilds:
  '@nestjs/core': false
  esbuild: true
  lefthook: true

ignoredBuiltDependencies:
  - lefthook

minimumReleaseAge: 0
