// MCP server (tool handlers + factory)

export { MCP_TOOL_COUNT } from "./constants.js";
export {
  appendMcpAuditEvent,
  createThingdMcpServer,
  jsonResult,
  parseCollectionAllowlist,
  parsePayloadSizeLimit,
  type RegisterThingdToolsOptions,
  readMcpHardeningOptionsFromEnv,
  registerThingdTools,
  resolveThingdMcpAuditOptions,
  type ThingdMcpAuditMetadata,
  type ThingdMcpAuditOptions,
  type ThingdMcpHardeningOptions,
  type ThingdMcpServerOptions,
} from "./mcp/index.js";
// REST API (route handlers + helpers)
export {
  handleRestRequest,
  parseFilter,
  parseIntParam,
  parseSortBy,
  readBody,
  sendData,
  sendDataList,
  sendError,
  sendJson,
} from "./rest/index.js";
export { Scheduler } from "./scheduler.js";
export type { CloudThingStoreOptions } from "./stores/cloud-thing-store.js";
export { CloudThingStore } from "./stores/cloud-thing-store.js";
export { InMemoryThingStore } from "./stores/in-memory-thing-store.js";
export type {
  MigrationRecord,
  SchemaDocument,
  StoredSchema,
} from "./stores/native-thing-store.js";
export { NativeThingStore, parseSchema } from "./stores/native-thing-store.js";
export type {
  ThingDDriver,
  ThingDEncryptionOptions,
  ThingDOpenConfig,
  ThingDOpenOptions,
} from "./thingd.js";
export { ThingD } from "./thingd.js";
export type {
  AggregateFunction,
  AggregateGroupResult,
  AggregateOptions,
  AggregateResult,
  BackupCapableThingStore,
  CollectionSchema,
  ConnectorAuth,
  ConnectorSchema,
  ConnectorSyncOptions,
  ConnectorSyncResult,
  FieldSchema,
  FilterOperator,
  Link,
  LinkDirection,
  LinkQueryOptions,
  ListEventsOptions,
  ListObjectsOptions,
  LocalThingDConnection,
  MemoryEvent,
  MemoryObject,
  MemoryQueue,
  MemorySearchOptions,
  MemorySearchResult,
  NlqIntent,
  NlqOptions,
  NlqResult,
  PutOptions,
  QueueClaimOptions,
  QueueJob,
  QueueJobOptions,
  QueueJobPayload,
  QueueJobResult,
  QueueJobStatus,
  QueueNackOptions,
  ReconnectableThingStore,
  Schedule,
  ScheduleContext,
  ScheduleEvent,
  ScheduleHandler,
  ScheduleIntervalOptions,
  ScheduleOnceOptions,
  ScheduleOptions,
  SchedulerEventType,
  SchedulerFacade,
  SchedulerListener,
  SchedulerStats,
  SchemaOptions,
  SortBy,
  SortDirection,
  StoredMemoryEvent,
  StoredMemoryObject,
  ThingDConnection,
  ThingDeleteResult,
  ThingStore,
  TimeBucket,
  TimeSeriesBucket,
  TimeSeriesOptions,
  TimeSeriesResult,
  VectorSearchHit,
  VectorSearchOptions,
  WalCheckpointResult,
} from "./types.js";
export { SDK_VERSION } from "./version.js";
